server:
  port: 8083

spring:
  application:
    name: triage-service
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    exchange:
      receipt-failed: x.goods-receipt-failed
      receipt-return: x.goods-receipt-return
    queue:
      receipt-failed: q.goods-receipt-failed
      receipt-produce-1: q.goods-receipt-produce-1
      receipt-produce-2: q.goods-receipt-produce-2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2