server:
  port: 8081

spring:
  application:
    name: goods-receipt-producer
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    exchange:
      receipt-produce: x.goods-receipt-produce
    routing-key:
      receipt-produce-1: rk.goods-receipt-produce-1
      receipt-produce-2: rk.goods-receipt-produce-2