server:
  port: 8082

spring:
  application:
    name: goods-receipt-consumer
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    exchange:
      receipt-produce: x.goods-receipt-produce
      receipt-failed: x.goods-receipt-failed
    queue:
      receipt-produce-1: q.goods-receipt-produce-1
      receipt-produce-2: q.goods-receipt-produce-2
