server:
  port: 8082

spring:
  application:
    name: goods-receipt-consumer
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    exchange:
      receipt-produce: x.goods-receipt-produce
      receipt-failed: x.goods-receipt-failed
      receipt-retry-1: x.goods-receipt-retry-1
      receipt-retry-2: x.goods-receipt-retry-2
      dead-letter: x.goods-receipt-dl
    routing-key:
      receipt-produce-1: rk.goods-receipt-produce-1
      receipt-produce-2: rk.goods-receipt-produce-2
      dead-letter: rk.goods-receipt-dl
    queue:
      receipt-produce-1: q.goods-receipt-produce-1
      receipt-produce-2: q.goods-receipt-produce-2
      receipt-retry-1: q.goods-receipt-retry-1
      receipt-retry-2: q.goods-receipt-retry-2
    listener:
      simple:
        default-requeue-rejected: false
rabbitmq:
  retry:
    retry-queue-ttl: 2000
    count: 2
  message-ttl: 10000
